"""add task category

Revision ID: 88da474aea2d
Revises: 9035b476786f
Create Date: 2026-08-09 11:57:49.639533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88da474aea2d'
down_revision: Union[str, Sequence[str], None] = '9035b476786f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('category', sa.String(), nullable=False,server_default='General'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'category')
    # ### end Alembic commands ###
