"""add task completed status

Revision ID: 9035b476786f
Revises: 02826031dfe4
Create Date: 2026-08-09 09:19:36.045787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9035b476786f'
down_revision: Union[str, Sequence[str], None] = '02826031dfe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tasks',
        sa.Column(
            'completed',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()
        )
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'completed')
    # ### end Alembic commands ###
