"""add task reminded status

Revision ID: e5613c537b0d
Revises: 8071a9e1d070
Create Date: 2026-08-10 17:02:55.485960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5613c537b0d'
down_revision: Union[str, Sequence[str], None] = '8071a9e1d070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('reminded', sa.Boolean(), nullable=False,server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'reminded')
    # ### end Alembic commands ###
